# .github/workflows/test.yml
#
# Starter test workflow for a single JS library with unit tests.
# Rename to test.yml and customize for your project.
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: test
run-name: "test [${{ github.ref_name }}]"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci || npm install

      - run: npm test
