#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (C) 2025-2026 Polycode Limited
// scripts/build-web.cjs
// Usage: node .github/agentic-lib/scripts/build-web.cjs
//
// Builds the docs/ directory for web serving:
// 1. Creates docs/ and copies src/web/* into it
// 2. Generates docs/lib-meta.js with package metadata exports
// 3. Generates docs/lib-browser.js from src/lib/main.js (if it has named exports)
//
// This file is part of the Example Suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
// This file is licensed under the MIT License. For details, see LICENSE-MIT

const fs = require("fs");
const path = require("path");

const docsDir = path.resolve("docs");

// Step 1: Create docs/ and copy src/web/* if it exists
fs.mkdirSync(docsDir, { recursive: true });
fs.writeFileSync(path.join(docsDir, ".nojekyll"), "");

const webDir = path.resolve("src", "web");
if (fs.existsSync(webDir)) {
  for (const entry of fs.readdirSync(webDir, { withFileTypes: true })) {
    const src = path.join(webDir, entry.name);
    const dest = path.join(docsDir, entry.name);
    if (entry.isFile()) {
      fs.copyFileSync(src, dest);
    } else if (entry.isDirectory()) {
      fs.cpSync(src, dest, { recursive: true });
    }
  }
}

// Step 2: Generate docs/lib-meta.js with package metadata
const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
const metaLines = ["name", "version", "description"].map(
  (k) => `export const ${k} = ${JSON.stringify(pkg[k])};`
);
fs.writeFileSync(path.join(docsDir, "lib-meta.js"), metaLines.join("\n") + "\n");
console.log("Wrote docs/lib-meta.js");

// Step 3: Generate docs/lib-browser.js from src/lib/main.js named exports
// Parse the main module for `export function` and `export async function` declarations
// and re-emit them as a standalone browser-compatible module.
const mainPath = path.resolve("src", "lib", "main.js");
if (fs.existsSync(mainPath)) {
  const mainSrc = fs.readFileSync(mainPath, "utf8");
  // Match named export functions: export function foo(...) { ... } or export async function foo(...)
  const exportRegex = /^export\s+(async\s+)?function\s+(\w+)/gm;
  const exportNames = [];
  let match;
  while ((match = exportRegex.exec(mainSrc)) !== null) {
    exportNames.push(match[2]);
  }

  if (exportNames.length > 0) {
    // Extract the function bodies by finding each export function and copying it verbatim
    const lines = mainSrc.split("\n");
    const functionBodies = [];
    for (let i = 0; i < lines.length; i++) {
      if (/^export\s+(async\s+)?function\s+\w+/.test(lines[i])) {
        // Collect lines until we find the closing brace at column 0
        const fnLines = [lines[i]];
        let braceDepth = 0;
        for (let j = i; j < lines.length; j++) {
          for (const ch of lines[j]) {
            if (ch === "{") braceDepth++;
            if (ch === "}") braceDepth--;
          }
          if (j > i) fnLines.push(lines[j]);
          if (braceDepth === 0 && j >= i) {
            break;
          }
        }
        functionBodies.push(fnLines.join("\n"));
      }
    }

    const header = [
      "// docs/lib-browser.js",
      "// Generated browser-compatible module exposing named exports from src/lib/main.js.",
      "// Auto-generated by build-web.cjs — do not edit manually.",
      "",
    ].join("\n");

    fs.writeFileSync(
      path.join(docsDir, "lib-browser.js"),
      header + functionBodies.join("\n\n") + "\n"
    );
    console.log(
      `Wrote docs/lib-browser.js (${exportNames.length} exports: ${exportNames.join(", ")})`
    );
  }
}
