# Which agentic-lib workflow schedule should be used?
schedule: schedule-1

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: MISSION.md
  librarySourcesFilepath:
    path: SOURCES.md
    limit: 32
    permissions:
      - write
  libraryDocumentsPath:
    path: demo/library/
    limit: 8
    permissions:
      - write
  featuresPath:
    path: demo/features/
    limit: 3
    permissions:
      - write

  # Filepaths for engineer workflows
  contributingFilepath:
    path: CONTRIBUTING.md
  allTestsPaths:
    paths:
      - tests/unit/
      - demo/tests/
  targetTestsPath:
    path: demo/tests/
    permissions:
      - write
  allSourcePaths:
    paths:
      - src/lib/
      - demo/source/
  targetSourcePath:
    path: demo/source/
    permissions:
      - write
  dependenciesFilepath:
    path: package.json
  documentationPath:
    path: demo/docs/
    permissions:
      - write

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: .prettierrc
  lintingFilepath:
    path: eslint.config.js
  readmeFilepath:
    path: README.md

# Execution commands
buildScript: npm run build
testScript: npm test
mainScript: npm run start

# How many issues should be available to be picked up?
featureDevelopmentIssuesWipLimit: 2
maintenanceIssuesWipLimit: 2

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2

# Web publishing
docRoot: public
