# .github/workflows/automerge-on-check-suite.yml
name: Automerge on Check Suite
concurrency: automerge-${{ github.ref_name }}
run-name: "Automerge on Check Suite [${{ github.ref_name }}]"

on:
  check_suite:
    types:
      - completed

jobs:

  check-pr:
    if: github.event.check_suite.conclusion == 'success'
    permissions:
      contents: write
      pull-requests: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-automerge-find-pr-in-check-suite.yml@main'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-check-pr:
    needs:
      - check-pr
    if: needs.check-pr.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      pull-requests: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-automerge-label-issue.yml@main'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  review-issue-after-check-pr:
    needs:
      - label-issue-after-check-pr
    if: ${{ needs.label-issue-after-check-pr.outputs.issueNumber != '' }}
    permissions:
      contents: write
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-review-issue.yml@main'
    with:
      issueNumber: ${{ needs.label-issue-after-check-pr.outputs.issueNumber }}
      target: 'src/lib/main.js'
      buildScript: 'npm run build'
      testScript: 'npm test'
      mainScript: "node 'src/lib/main.js'"
      model: 'o3-mini'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}

  automerge:
    needs:
      - check-pr
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-automerge-merge-pr.yml@main'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-automerge:
    needs:
      - check-pr
      - automerge
    if: needs.automerge.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      #pull-requests: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-automerge-label-issue.yml@main'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  review-issue-after-automerge:
    needs:
      - label-issue-after-automerge
    if: ${{ needs.label-issue-after-automerge.outputs.issueNumber != '' }}
    permissions:
      contents: write
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-review-issue.yml@main'
    with:
      issueNumber: ${{ needs.label-issue-after-automerge.outputs.issueNumber }}
      target: 'src/lib/main.js'
      buildScript: 'npm run build'
      testScript: 'npm test'
      mainScript: "node 'src/lib/main.js'"
      model: 'o3-mini'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
