# .github/workflows/formating.yml
name: Formatting
run-name: "Formatting [${{ github.ref_name }}]"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:

  format-and-push:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-run-script-and-push-changes.yml@main'
    with:
      script: 'npm run formatting-fix src/lib/main.js ; npm run linting-fix src/lib/main.js'
      testScript: 'npm test'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      gitCommitMessage: 'Updated by `prettier --write`'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
